services:
  db:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
