# Generated by Django 5.2.12 on 2026-05-02 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15, verbose_name='カテゴリー名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Extensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10, verbose_name='拡張子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'extension',
            },
        ),
        migrations.CreateModel(
            name='Random_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_name', models.CharField(max_length=50, verbose_name='ランダム名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Random_name',
            },
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, verbose_name='コマンド')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('target_type', models.CharField(choices=[('file', 'ファイル'), ('directory', 'ディレクトリ'), ('none', 'なし')], default='none', max_length=15, verbose_name='タイプ判別')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycom.categories', verbose_name='カテゴリーID')),
            ],
            options={
                'verbose_name_plural': 'command',
            },
        ),
        migrations.CreateModel(
            name='Accuracies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_rate', models.FloatField(verbose_name='正解率')),
                ('challenge_count', models.PositiveIntegerField(verbose_name='挑戦回数')),
                ('correct_count', models.PositiveIntegerField(verbose_name='正解回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycom.commands', verbose_name='コマンドID')),
            ],
            options={
                'verbose_name_plural': 'accuracy',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='問題文')),
                ('description', models.TextField(verbose_name='説明文')),
                ('answer', models.CharField(max_length=100, verbose_name='答え')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycom.commands', verbose_name='コマンドID')),
            ],
            options={
                'verbose_name_plural': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tycom.categories', verbose_name='カテゴリーID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'score',
            },
        ),
    ]
