# Generated by Django 5.2.12 on 2026-05-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(max_length=200, verbose_name='コマンド'),
        ),
    ]
